site_name: Minnah Project Documentation

theme: material
nav:
  - Introduction: 'introduction.md'
  - Purpose: 'purpose.md'
  - System Studies: 'system_studies.md'
  - System Design: 'system_design.md'
  - External Interface Requirements: 'external_interface_requirements.md'
  - System Features: 'system_features.md'
  - Functional Requirements: 'functional_requirements.md'
  - Non-functional Requirements: 'non_functional_requirements.md'
  - Interaction with Humans: 'interaction_with_humans.md'
  - Conclusion: 'conclusion.md'
